export const REGISTRATION_REQUEST: "REGISTRATION_REQUEST" = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS" = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR: "REGISTRATION_ERROR" = "REGISTRATION_ERROR";
export const LOGIN_REQUEST: "LOGIN_REQUEST" = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_ERROR: "LOGIN_ERROR" = "LOGIN_ERROR";
export const USER_REQUEST: "USER_REQUEST" = "USER_REQUEST";
export const USER_SUCCESS: "USER_SUCCESS" = "USER_SUCCESS";
export const USER_ERROR: "USER_ERROR" = "USER_ERROR";
export const PATCH_USER_REQUEST: "PATCH_USER_REQUEST" = "PATCH_USER_REQUEST";
export const PATCH_USER_SUCCESS: "PATCH_USER_SUCCESS" = "PATCH_USER_SUCCESS";
export const PATCH_USER_ERROR: "PATCH_USER_ERROR" = "PATCH_USER_ERROR";
export const LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST" = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS" = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR" = "LOGOUT_USER_ERROR";

export const PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST" = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS" = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_ERROR: "PASSWORD_RESET_ERROR" = "PASSWORD_RESET_ERROR";
export const PASSWORD_RECOVERY_SUCCESS: "PASSWORD_RECOVERY_SUCCESS" = "PASSWORD_RECOVERY_SUCCESS";
export const PASSWORD_RECOVERY_REQUEST: "PASSWORD_RECOVERY_REQUEST" = "PASSWORD_RECOVERY_REQUEST";
export const PASSWORD_RECOVERY_ERROR: "PASSWORD_RECOVERY_ERROR" = "PASSWORD_RECOVERY_ERROR";
export const PASSWORD_RECORD: "PASSWORD_RECORD" = "PASSWORD_RECORD";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const RESET_INGREDIENTS: "RESET_INGREDIENTS" = "RESET_INGREDIENTS";
export const SORT_INGREDIENTS: "SORT_INGREDIENTS" = "SORT_INGREDIENTS"
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";

export const INGREDIENTS_DATA_SUCCESS: "INGREDIENTS_DATA_SUCCESS" = "INGREDIENTS_DATA_SUCCESS";
export const INGREDIENTS_DATA_REQUEST: "INGREDIENTS_DATA_REQUEST" = "INGREDIENTS_DATA_REQUEST";
export const INGREDIENTS_DATA_ERROR: "INGREDIENTS_DATA_ERROR" = "INGREDIENTS_DATA_ERROR";

export const ORDER_DATA_SUCCESS: "ORDER_DATA_SUCCESS" = "ORDER_DATA_SUCCESS";
export const ORDER_DATA_REQUEST: "ORDER_DATA_REQUEST" = "ORDER_DATA_REQUEST";
export const ORDER_DATA_ERROR: "ORDER_DATA_ERROR" = "ORDER_DATA_ERROR";
export const ORDER_DATA_DELETE: "ORDER_DATA_DELETE" = "ORDER_DATA_DELETE";

export const FEED_CONNECT: "FEED_CONNECT" = "FEED_CONNECT";
export const FEED_DISCONNECT: "FEED_DISCONNECT" = "FEED_DISCONNECT";
export const FEED_WS_CONNECT: "FEED_WS_CONNECT" = "FEED_WS_CONNECT";
export const FEED_WS_OPEN: "FEED_WS_OPEN" = "FEED_WS_OPEN";
export const FEED_WS_CLOSE: "FEED_WS_CLOSE" = "FEED_WS_CLOSE";
export const FEED_WS_ERROR: "FEED_WS_ERROR" = "FEED_WS_ERROR";
export const FEED_WS_MESSAGE: "FEED_WS_MESSAGE" = "FEED_WS_MESSAGE";

export const ORDERS_CONNECT: "ORDERS_CONNECT" = "ORDERS_CONNECT";
export const ORDERS_DISCONNECT: "ORDERS_DISCONNECT" = "ORDERS_DISCONNECT";
export const ORDERS_WS_CONNECT: "ORDERS_WS_CONNECT" = "ORDERS_WS_CONNECT";
export const ORDERS_WS_OPEN: "ORDERS_WS_OPEN" = "ORDERS_WS_OPEN";
export const ORDERS_WS_CLOSE: "ORDERS_WS_CLOSE" = "ORDERS_WS_CLOSE";
export const ORDERS_WS_ERROR: "ORDER_WS_ERROR" = "ORDER_WS_ERROR";
export const ORDERS_WS_MESSAGE: "ORDER_WS_MESSAGE" = "ORDER_WS_MESSAGE";




